### PR TITLE
Fix for allowing objects on the internal model for multi-selects

### PR DESCRIPTION
**Pull request by CrouseMatthew**

### CODE REVIEW

**Comment by nicklasb** [comment]
Awaiting final PR. :-)

**Comment by CrouseMatthew** [comment]
Yeah sorry about that. I am a Jr. Developer and this is the first time I
have done a pull request on a opensource project. I meant to do a pull
request on a forked version in our corporate repo. Once that goes through
some testing I will open a PR.

again, sorry about that.

**Comment by nicklasb** [comment]
No worries, PR:s are a bit tricky to wrap one's head around in the beginning.

**Comment by nicklasb** [comment]
@tombriles,  @CrouseMatthew : WRT tricky, ui-select is, and regrettably the ASFDS implementation of it is too. 
I'd like to add that I have tried improving on that several times, always failing and returning to the current solution. :-/

**Pull request closed without merging**
