### PR TITLE
First version of ui - select bug fixed

### PR DESCRIPTION
**Pull request by ngpatel143**

### CODE REVIEW

**Comment by nicklasb** [comment]
Great! (but ouch, the github differ really sucks)
I'll take a look and get back to you.

**Comment by nicklasb** [comment]
Whatever, I have to merge it to look at it, basically.

**Comment by nicklasb** [comment]
So, there are a couple of things.  
Do not be offended, it is great that you have fixed the bug, but there are several things to adress:
1. src/uiselect.html: You have removed the tagging support. Why? (I know that it looks like hell, but it is not much one can do about that, on the other hand I don't really know if it works properly, but that is hard to test if it isn't there)
2. root/src/angular-schema-form-dynamic-select.js: In the top of the file, you have added the minified template cache. That is not supposed to be there, the template cache is automatically added to root/angular-schema-form-dynamic-select.js by gulp . The /src-files aren't supposed to be used except for editing, when one wants to look at what one has done, one must run `gulp default` . This is for several reasons.
   Please look at the build-section in the docs on how to install gulp:
   https://github.com/OptimalBPM/angular-schema-form-dynamic-select#building
3. root/src/angular-schema-form-dynamic-select.js: The indentation is not correct, it is a good idea to always use a formatting tool. With regards to the fix of the bug itself, it seems good.
4. index.html: You have changed it considerably:
   
   A. I do not want to remove the explanatory texts in the top of the example page. I want the demo page to be understandable and the example to be identical to the demo page.
   
   B. There are now absolute references to files under http://demo.optimalbpm.se/angular-schema-form-dynamic-select, which is not a good idea. If someone just want to look at an example, they should go to the demo page, if they want to develop the plugin, they need follow the instructions to install all dependencies(it only takes 10 minutes). And also for the reasons in A. And also because it causes errors due to me not wanting to set the 'Access-Control-Allow-Origin' header for the demo site, that is not how it is supposed to be used.
   
   C. The underscore/jquery-ui-dependencies are removed. There was some edge-case issues with one one them that I can't remember right now, but I don't know if they still apply. So maybe anyway. 
5. Commits: To use git properly; make smaller commits, this is more like four commits(I would refrain from B and A and try to make the tagging support work with your new code):
   
   A. for the removal of tagging support
   
   B. the removal of the explanatory text 
   
   C. the removal of the jquery-ui dependency.
   
   D. the fix of the bug in /src/angular-schema-form-dynamic-select.js and the correction of the value to "value1" in app.js.

_And in each commit, any changes in root/angular-schema-form-dynamic-select.js resulting from rebuilding needs to be included._

Now, don't be alarmed by all these things, I really appreciate your work. These are friendly tips, me trying to help you along. Each and every project manager would basically say the same things.

Fix them, and you can make a PR to develop instead next time.

**Comment by nicklasb** [comment]
I can remove the above message later if you feel that you perhaps is cast in a bad light. I don't wish to cause you any problems.

**Comment by ngpatel143** [comment]
HI Sorry for my commit i will revert my commit and i will push my modification, because i did just little modifications. thanks

**Comment by nicklasb** [comment]
No problems.

**Comment by nicklasb** [comment]
@ngpatel143, I haven't heard from you in a while on this, therefore I will add this myself instead.

**Comment by nicklasb** [comment]
@ngpatel143: Note: This was fixed in 1e0e184e9fb42d907ba825b482e67c4bd6127fb1.

**Pull request merged**
