### PR TITLE
Release 0.12.5

### PR DESCRIPTION
**Pull request by jubianchi**
Any chance to see a new release of the package including the #53 ?

thanks :)

### CODE REVIEW

**Comment by nicklasb** [comment]
Yes, as soon as i return from my vacation. :-)

(Meanwhile use #master..)

**Comment by jubianchi** [comment]
@nicklasb no problem! Thanks!

**Comment by nicklasb** [comment]
Hm, I am sorry, but it seems I have forgotten about this one, is it possible for you to redo this on the develop branch?

**Comment by jubianchi** [comment]
of course ;)

**Comment by philibe** [comment]
:+1:   :)

**Comment by nicklasb** [comment]
Good stuff!

**Pull request closed without merging**
