### PR TITLE
Field name and check for data field in asyncCallback

### PR DESCRIPTION
**Pull request by LeonardoGentile**
See #82 and https://github.com/OptimalBPM/angular-schema-form-dynamic-select/issues/81#issuecomment-215942323

### CODE REVIEW

**Comment by nicklasb** [comment]
Thanks a bunch! Looks good!

If you have any more things you want to do, I could add you to the project?

**Comment by nicklasb** [comment]
Because you seem to be invested in the ui-selects, which I am not that terribly myself.

**Comment by LeonardoGentile** [comment]
@nicklasb yes, if you want I could help you. I am indeed more interested in ui-select instead of strapselects.

In fact I wanted to propose you to keep the main commonalities between the two but then split the project  in two because the ones who uses ui-select do not need strapselects (and the extra code) and vice-versa

**Comment by nicklasb** [comment]
Great! (however there is not actually that much code, and there are several that uses both)

**Pull request merged**
