### PR TITLE
Allow internalModel objects to be more complex

### PR DESCRIPTION
**Pull request by ghost**
This change will allow additional attributes to exist on an object in internalModel. My use case is to style selected pills dynamically based upon the values of particular attributes.

It should not affect current functionality.

### CODE REVIEW

**Comment by ghost** [comment]
Is there a plan to merge this (and #95)?

**Comment by nicklasb** [comment]
Well yeah I have for some reason basically failed to see these. I will check them tomorrow!

I am sorry for not responding!

**Comment by ghost** [comment]
Heh. That was quick. Thanks. ;)

**Comment by nicklasb** [comment]
If I am awake, I respond pretty quickly.

**Comment by albertjose** [comment]
Is there a plan to merge this²?

**Comment by nicklasb** [comment]
I seem to simply have forgotten about it completely, sorry about that. Seems legit to me.

**Pull request merged**
